// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtGibf81PvYAoXzn38lYf8_cIEwRCHtwI',
    appId: '1:166566026141:web:84ea12f14a6e5a5a42ed74',
    messagingSenderId: '166566026141',
    projectId: 'ml-model-30157',
    authDomain: 'ml-model-30157.firebaseapp.com',
    storageBucket: 'ml-model-30157.appspot.com',
    measurementId: 'G-68PS0L555Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjmE88U3BwyUqbDQqmVw9O1KYyf4dDZg',
    appId: '1:166566026141:android:34057bce6b23bec042ed74',
    messagingSenderId: '166566026141',
    projectId: 'ml-model-30157',
    storageBucket: 'ml-model-30157.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALIVejOZP5jiZSkfjcezl3fxK5NNH6Sv8',
    appId: '1:166566026141:ios:a8bd6c2c1e9c5c9342ed74',
    messagingSenderId: '166566026141',
    projectId: 'ml-model-30157',
    storageBucket: 'ml-model-30157.appspot.com',
    iosBundleId: 'com.example.mlModelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALIVejOZP5jiZSkfjcezl3fxK5NNH6Sv8',
    appId: '1:166566026141:ios:747c8a3ecd47e9f642ed74',
    messagingSenderId: '166566026141',
    projectId: 'ml-model-30157',
    storageBucket: 'ml-model-30157.appspot.com',
    iosBundleId: 'com.example.mlModelApp.RunnerTests',
  );
}
